<?php

?>

<!DOCTYPE html>
<html>
    <head>
        <title>Ex form</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="style.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <h2>NOM Prénom</h2>
            <p>Intitulé du poste</p>
        </header>
        <main>
            <section>
                <h1>Informations</h1>
                <h4>Contact</h4>
                <h3>Email</h3>
                <p>email@example.com</p>
                <h3>Téléphone</h3>
                <p>01 02 03 04 05</p>
                <h3>LinkedIn</h3>
                <p>https://linkedin.com/example</p>
                <h3>GitHub</h3>
                <p>https://github.com/example</p>
                <h4>Biographie</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, sed, fugit, beatae doloremque nisi deserunt consequuntur non perferendis 
                quisquam eum sequi similique odio numquam alias culpa dolorem adipisci. Praesentium, ut.</p>
                <h4>Loisirs</h4>
                <ul>
                    <li>Jeux de stratégie</li>
                    <li>Violon</li>
                    <li>Roller Derby</li>
                    <li>Voile</li>
                </ul>
            </section>
            <section>
                <h1>Compétences</h1>
                <h4>Langages des programmations</h4>
                <ul>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>JavaScript</li>
                    <li>PHP</li>
                    <li>SQL</li>
                </ul>
                <h4>Frameworks & Librairies</h4>
                <ul>
                    <li>Sass</li>
                    <li>Bootstrap</li>
                    <li>Symfony</li>
                    <li>Laravel</li>
                </ul>
                <h4>Logiciels</h4>
                <ul>
                    <li>Photoshop</li>
                    <li>Illustrator</li>
                    <li>XD</li>
                    <li>Figma</li>
                </ul>
                <h4>Langues</h4>
                <ul>
                    <li>Anglais</li>
                    <li>Français</li>
                    <li>Arabe</li>
                </ul>
            </section>
        </main>
    </body>
</html>